version: 2.1

# Jobs qui seront executés
jobs:
  build:
    # Environnement Java 8 ou supérieur
    docker:
      - image: cimg/openjdk:19.0.2

    steps:
      - checkout

      # Installation de Maven
      - run:
          name: Install Maven
          command: |
            mvn --version || sudo apt-get update && sudo apt-get install -y maven

      - run:
          name: Build
          command: mvn -B -DskipTests clean package


      # Execution des tests unitaires avec Maven
      - run:
          name: Run unit tests
          command: |
            mvn clean test

# Workflows
workflows:
  version: 2.1
  build:
    jobs:
      - build:
        # Execution uniquement sur la branche "master"
        filters:
          branches:
            only:
            -  master
