version: 2.1
orbs:
  codecov: codecov/codecov@3.2.4

# Simple commentaire pour valider le rendu du TP2
# Jobs qui seront executés
jobs:
  build:
    # Environnement Java 8 ou supérieur
    docker:
      - image: cimg/openjdk:19.0.2

    steps:
      - checkout

      - run:
          name: Build
          command: mvn -B -DskipTests clean package


      # Execution des tests unitaires avec Maven
      - run:
          name: Run unit tests
          command: |
            mvn clean test
      - codecov/upload
  
  docs:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: OpenJDK-PPA
          command: sudo add-apt-repository ppa:openjdk-r/ppa
      - run:
          name: Update
          command: sudo apt-get update
      - run:
          name: OpenJDK-Install
          command: sudo apt-get install openjdk-11-jdk-headless -y
      - run:
          name: Docs-Build
          command: javadoc -d docs src/main/java/fr/univavignon/pokedex/api/* 
      - persist_to_workspace:
          root: .
          paths: docs

  docs-deploy:
    docker:
      - image: node:20
    steps:
      - checkout
      - attach_workspace:
          at: docs/
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@3.0.0
            git config user.email "explo8413@gmail.com"
            git config user.name "Théo Quezel-Perron"
      - add_ssh_keys:
          fingerprints:
            - "e4:3a:98:b2:d1:c5:30:d5:c9:e1:40:9f:c3:2e:bd:59"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist docs/

# Workflows
workflows:
  version: 2.1
  build:
    jobs:
      - build:
        # Execution uniquement sur la branche "master"
        filters:
          branches:
            only:
            -  master
      - docs
      - docs-deploy:
          requires:
            - docs
