version: 2.1

# Jobs qui seront executés
jobs:
  build:
    # Execution uniquement sur la branche "master"
    branches:
      only:
        - master
    # Environnement Java 8 ou supérieur
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout

      # Installation de Maven
      - run:
          name: Install Maven
          command: |
            mvn --version || sudo apt-get update && sudo apt-get install -y maven

      # Execution des tests unitaires avec Maven
      - run:
          name: Run unit tests
          command: |
            mvn clean test

# Workflows
workflows:
  version: 2.1
  build:
    jobs:
      - build
