version: 2.1
orbs:
  codecov: codecov/codecov@3.2.4

# Simple commentaire pour valider le rendu du TP2
# Jobs qui seront executés
jobs:
  build:
    # Environnement Java 8 ou supérieur
    docker:
      - image: cimg/openjdk:19.0.2

    steps:
      - checkout

      - run:
          name: Build
          command: mvn -B -DskipTests clean package


      # Execution des tests unitaires avec Maven
      - run:
          name: Run unit tests
          command: |
            mvn clean test
      - codecov/upload

# Workflows
workflows:
  version: 2.1
  build:
    jobs:
      - build:
        # Execution uniquement sur la branche "master"
        filters:
          branches:
            only:
            -  master
