name: Codecov

on:
  push:
    branches:
      - master

jobs:
  codecov:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Codecov
        run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: 0bc5bccf-ffca-48fe-acc6-6c5b231c133a
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
